# Generated by Django 4.1.6 on 2025-03-15 20:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_aboutsiteconfig_markdown_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutsiteconfig",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="aboutsiteconfig",
            name="resume",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="raw"
            ),
        ),
    ]
