# Generated by Django 4.1.6 on 2025-03-15 20:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0002_rename_isntagramm_socialaccountsconfig_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainconfig",
            name="favicon",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
