# Generated by Django 4.1.6 on 2025-03-15 20:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
