# Generated by Django 4.1.6 on 2026-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certification_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('journal', models.CharField(help_text='Name of the journal or conference.', max_length=255, verbose_name='Journal / Conference')),
                ('date', models.DateField(verbose_name='Publication Date')),
                ('abstract', models.TextField(blank=True, help_text='Brief abstract or summary of the paper.', null=True)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier (e.g. 10.1234/example).', max_length=255, null=True, verbose_name='DOI')),
                ('url', models.URLField(blank=True, help_text='Link to the published paper.', null=True, verbose_name='Paper URL')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date'],
            },
        ),
    ]
